nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: BileMo portfolio and users management
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/(?!doc|items/c) # Accepts routes under /api except /doc and /items/c