nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: Catalogue BileMo et gestion de vos utilisateurs
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/doc$) # Accepts routes under /api except /api/doc
